on:
  push:
  workflow_dispatch:

name: GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/closehandle/fakehttp:latest
          context: .

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write
